### ISSUE TITLE
Geocoder exception

### ISSUE THREAD

**Issue by karlhe** [karlhe/pokemongo-notifier#3]
Ran into this exception after running for a few days:

```
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\tools\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\tools\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "main.py", line 588, in main
    pokemonsJSON, ignore, only, notify_ignore)
  File "main.py", line 712, in process_step
    notifier.pokemon_found(pokemon_obj)
  File "c:\dev\pokemongo-notifier\notifier.py", line 30, in pokemon_found
    location = Nominatim().reverse(coords)
  File "C:\tools\Python27\lib\site-packages\geopy\geocoders\osm.py", line 248, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\tools\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
GeocoderTimedOut: Service timed out
```

corresponds to this line: `location = Nominatim().reverse(coords)`

Need to catch that exception...

**Comment by karlhe** [comment]
Resolved by removing this feature, which wasn't all that useful anyway.

Will look into adding something for user-defined location names or something like #2.
